#!/usr/bin/env bash

# script name: dm-usbmount
# Description: Mount/unmount usb drives using dmenu. No fancy daemon required.
# Dependencies: dmenu

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

declare dmscript_path="/home/jvh/.local/dmscripts"

# Rofi CMD
rofi_cmd() {
  rofi -dmenu \
    -p "DM-script: " \
    -theme "catppuccin-frappe-side.rasi" \
    -sidebar-mode
}

run_cmd() {
  ${dmscript_path}/dm-${1} -r
}

main() {
  # position mouse on screen 1
  xdotool mousemove --screen 0 1850 1030
  xdotool click 1

  files="$(find ${dmscript_path}/ -maxdepth 1 -iname "dm-*")"
  tools=$(printf '%s\n' "${files[@]}" | xargs basename -a | cut -d '-' -f2- | sort)

  choice="$(printf '%s' "${tools}" | rofi_cmd)"

  [ -n "${choice}" ] && run_cmd ${choice}
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"

# vim: ts=2 sts=2 sw=2 et
